import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { prisma } from './db.js';
import { requireRoles } from './auth.js';

export function registerCoreRoutes(app:FastifyInstance){
  app.get('/year-groups',async()=>prisma.yearGroup.findMany({orderBy:{year:'desc'},include:{_count:{select:{memberships:true}}}}));
  app.post('/year-groups',{preHandler:[app.authenticate,requireRoles('ADMIN','SUPER_ADMIN')]},async(req)=>{const b=z.object({year:z.number().int(),name:z.string().min(2),description:z.string().optional()}).parse(req.body);return prisma.yearGroup.create({data:b});});
  app.post('/year-groups/:id/join',{preHandler:[app.authenticate]},async(req:any)=>prisma.yearGroupMembership.upsert({where:{userId_yearGroupId:{userId:req.user.sub,yearGroupId:req.params.id}},update:{},create:{userId:req.user.sub,yearGroupId:req.params.id}}));

  app.get('/alumni',{preHandler:[app.authenticate]},async(req:any)=>{const q=z.object({year:z.coerce.number().optional(),house:z.string().optional(),search:z.string().optional()}).parse(req.query);return prisma.alumniProfile.findMany({where:{searchable:true,graduationYear:q.year,house:q.house,fullName:q.search?{contains:q.search,mode:'insensitive'}:undefined},take:100,select:{fullName:true,graduationYear:true,house:true,country:true,city:true,profession:true,avatarUrl:true,userId:true}})});
  app.patch('/profile',{preHandler:[app.authenticate]},async(req:any)=>{const b=z.object({fullName:z.string().min(2).optional(),house:z.string().optional(),className:z.string().optional(),positionHeld:z.string().optional(),country:z.string().optional(),city:z.string().optional(),profession:z.string().optional(),bio:z.string().max(1000).optional(),avatarUrl:z.string().url().optional(),searchable:z.boolean().optional()}).parse(req.body);return prisma.alumniProfile.update({where:{userId:req.user.sub},data:b});});

  app.post('/support',{preHandler:[app.authenticate]},async(req:any)=>{const b=z.object({subject:z.string().min(3),body:z.string().min(5)}).parse(req.body);return prisma.supportTicket.create({data:{userId:req.user.sub,...b}})});
  app.get('/support/my',{preHandler:[app.authenticate]},async(req:any)=>prisma.supportTicket.findMany({where:{userId:req.user.sub},orderBy:{createdAt:'desc'}}));

  app.get('/projects',async()=>prisma.project.findMany({where:{status:{in:['ACTIVE','FUNDED','IN_PROGRESS','COMPLETED']}},orderBy:{createdAt:'desc'}}));
  app.post('/projects',{preHandler:[app.authenticate,requireRoles('YEAR_ADMIN','ADMIN','SUPER_ADMIN')]},async(req)=>{const b=z.object({title:z.string(),description:z.string(),targetAmount:z.number().positive(),yearGroupId:z.string().optional()}).parse(req.body);return prisma.project.create({data:{...b,status:'ACTIVE'}})});
  app.post('/projects/:id/contribute',{preHandler:[app.authenticate]},async(req:any)=>{const b=z.object({amount:z.number().positive(),anonymous:z.boolean().default(false)}).parse(req.body);return prisma.$transaction(async tx=>{const c=await tx.contribution.create({data:{projectId:req.params.id,userId:req.user.sub,amount:b.amount,anonymous:b.anonymous}});await tx.project.update({where:{id:req.params.id},data:{raisedAmount:{increment:b.amount}}});return c;});});

  app.get('/events',async()=>prisma.event.findMany({orderBy:{startsAt:'asc'}}));
  app.post('/events',{preHandler:[app.authenticate,requireRoles('ADMIN','SUPER_ADMIN')]},async(req)=>{const b=z.object({title:z.string(),description:z.string().optional(),startsAt:z.string().datetime(),endsAt:z.string().datetime().optional(),venue:z.string().optional(),streamUrl:z.string().url().optional(),ticketPrice:z.number().nonnegative().optional()}).parse(req.body);return prisma.event.create({data:{...b,startsAt:new Date(b.startsAt),endsAt:b.endsAt?new Date(b.endsAt):undefined}})});

  app.get('/businesses',async()=>prisma.business.findMany({where:{verified:true},take:100}));
  app.post('/businesses',{preHandler:[app.authenticate]},async(req:any)=>{const b=z.object({name:z.string().min(2),category:z.string().min(2),description:z.string().optional(),website:z.string().url().optional(),phone:z.string().optional(),logoUrl:z.string().url().optional()}).parse(req.body);return prisma.business.create({data:{ownerId:req.user.sub,...b}})});
  app.post('/businesses/:id/ads',{preHandler:[app.authenticate]},async(req:any,reply)=>{const business=await prisma.business.findFirst({where:{id:req.params.id,ownerId:req.user.sub}});if(!business)return reply.code(404).send({error:'Business not found'});const b=z.object({placement:z.enum(['year_group','home','events','platform_wide']),durationDays:z.number().int().positive(),audience:z.string(),quotedAmount:z.number().positive(),creativeUrl:z.string().url().optional()}).parse(req.body);return prisma.adCampaign.create({data:{businessId:business.id,...b,status:'PENDING_APPROVAL'}})});

  app.get('/chat/rooms',{preHandler:[app.authenticate]},async()=>prisma.chatRoom.findMany({orderBy:{createdAt:'asc'},include:{_count:{select:{messages:true}},yearGroup:{select:{year:true,name:true}}}}));
  app.post('/chat/rooms',{preHandler:[app.authenticate]},async(req)=>{const b=z.object({name:z.string().min(2),yearGroupId:z.string().optional(),isAssemblyHall:z.boolean().default(false)}).parse(req.body);return prisma.chatRoom.create({data:b})});
  app.get('/chat/rooms/:id/messages',{preHandler:[app.authenticate]},async(req:any)=>{const q=z.object({cursor:z.string().optional(),limit:z.coerce.number().int().min(1).max(100).default(50)}).parse(req.query);return prisma.message.findMany({where:{roomId:req.params.id},orderBy:{createdAt:'desc'},take:q.limit,...(q.cursor?{skip:1,cursor:{id:q.cursor}}:{}) ,include:{user:{select:{profile:{select:{fullName:true,avatarUrl:true}}}}}})});
  app.post('/chat/rooms/:id/messages',{preHandler:[app.authenticate]},async(req:any)=>{const b=z.object({body:z.string().min(1).max(4000)}).parse(req.body);return prisma.message.create({data:{roomId:req.params.id,userId:req.user.sub,body:b.body}})});

  app.get('/elections',{preHandler:[app.authenticate]},async()=>prisma.election.findMany({orderBy:{opensAt:'desc'},include:{_count:{select:{candidates:true,votes:true}},yearGroup:{select:{year:true,name:true}}}}));
  app.post('/elections',{preHandler:[app.authenticate,requireRoles('YEAR_ADMIN','ADMIN','SUPER_ADMIN')]},async(req)=>{const b=z.object({title:z.string().min(2),description:z.string().optional(),yearGroupId:z.string().optional(),opensAt:z.string().datetime(),closesAt:z.string().datetime()}).parse(req.body);return prisma.election.create({data:{...b,opensAt:new Date(b.opensAt),closesAt:new Date(b.closesAt),status:'SCHEDULED'}})});
  app.post('/elections/:id/candidates',{preHandler:[app.authenticate,requireRoles('YEAR_ADMIN','ADMIN','SUPER_ADMIN')]},async(req:any)=>{const b=z.object({userId:z.string(),position:z.string(),manifesto:z.string().optional()}).parse(req.body);return prisma.candidate.create({data:{electionId:req.params.id,...b}})});
  app.get('/elections/:id', {preHandler:[app.authenticate]}, async(req:any)=>prisma.election.findUnique({where:{id:req.params.id},include:{candidates:true}}));
  app.get('/elections/:id/results',{preHandler:[app.authenticate]},async(req:any,reply)=>{const election=await prisma.election.findUnique({where:{id:req.params.id}});if(!election)return reply.code(404).send({error:'Election not found'});if(!['CLOSED','CERTIFIED'].includes(election.status)&&!['ADMIN','SUPER_ADMIN'].includes(req.user.role))return reply.code(403).send({error:'Results are not public yet'});return prisma.vote.groupBy({by:['candidateId','position'],where:{electionId:election.id},_count:{_all:true}})});
  app.post('/elections/:id/vote',{preHandler:[app.authenticate]},async(req:any,reply)=>{const b=z.object({candidateId:z.string(),position:z.string()}).parse(req.body);const e=await prisma.election.findUnique({where:{id:req.params.id}});if(!e||e.status!=='OPEN'||new Date()<e.opensAt||new Date()>e.closesAt)return reply.code(409).send({error:'Election is not open'});const candidate=await prisma.candidate.findFirst({where:{id:b.candidateId,electionId:e.id,position:b.position}});if(!candidate)return reply.code(400).send({error:'Invalid candidate'});try{return await prisma.vote.create({data:{electionId:e.id,candidateId:b.candidateId,voterId:req.user.sub,position:b.position}})}catch{return reply.code(409).send({error:'You have already voted for this position'});}});

  app.get('/admin/stats',{preHandler:[app.authenticate,requireRoles('ADMIN','SUPER_ADMIN')]},async()=>{const [users,verified,projects,payments,openTickets,pendingAds,pendingQuotes]=await Promise.all([prisma.user.count(),prisma.user.count({where:{verification:'VERIFIED'}}),prisma.project.count(),prisma.payment.aggregate({_sum:{amount:true},where:{status:'PAID'}}),prisma.supportTicket.count({where:{status:{in:['OPEN','IN_PROGRESS']}}}),prisma.adCampaign.count({where:{status:'PENDING_APPROVAL'}}),prisma.quote.count({where:{status:{in:['DRAFT','SENT']}}})]);return{users,verified,projects,revenue:payments._sum.amount??0,openTickets,pendingAds,pendingQuotes};});
  app.get('/admin/members/pending',{preHandler:[app.authenticate,requireRoles('ADMIN','SUPER_ADMIN')]},async()=>prisma.user.findMany({where:{verification:'PENDING'},select:{id:true,email:true,phone:true,createdAt:true,profile:true}}));
  app.post('/admin/members/:id/verify',{preHandler:[app.authenticate,requireRoles('ADMIN','SUPER_ADMIN')]},async(req:any)=>prisma.user.update({where:{id:req.params.id},data:{verification:'VERIFIED'}}));
  app.post('/admin/ads/:id/approve',{preHandler:[app.authenticate,requireRoles('ADMIN','SUPER_ADMIN')]},async(req:any)=>prisma.adCampaign.update({where:{id:req.params.id},data:{status:'APPROVED'}}));
  app.get('/admin/quotes',{preHandler:[app.authenticate,requireRoles('ADMIN','SUPER_ADMIN')]},async()=>prisma.quote.findMany({orderBy:{createdAt:'desc'},include:{intake:true,items:true}}));
  app.post('/admin/quotes/:id/approve',{preHandler:[app.authenticate,requireRoles('ADMIN','SUPER_ADMIN')]},async(req:any)=>prisma.quote.update({where:{id:req.params.id},data:{status:'SENT'}}));
}
