import Fastify from 'fastify';
import cors from '@fastify/cors';
import helmet from '@fastify/helmet';
import jwt from '@fastify/jwt';
import rateLimit from '@fastify/rate-limit';
import { env } from './config.js';
import { registerAuthRoutes } from './auth.js';
import { registerCoreRoutes } from './routes.js';
import { registerAiRoutes } from './ai.js';
import { registerLiveRoutes } from './live.js';
import { registerPaymentRoutes } from './payments.js';

const app=Fastify({logger:{redact:['req.headers.authorization']},trustProxy:true,bodyLimit:2_000_000});
await app.register(helmet,{global:true});
const isDev = env.NODE_ENV !== 'production';
const allowedOrigins = isDev ? true : [env.WEB_URL, 'https://opass-connect.vercel.app', 'https://opass-connect-*.vercel.app'];
await app.register(cors,{origin: allowedOrigins, credentials:true});
await app.register(rateLimit,{max:120,timeWindow:'1 minute'});
await app.register(jwt,{secret:env.JWT_SECRET});
app.decorate('authenticate',async function(request:any,reply:any){try{await request.jwtVerify();}catch{return reply.code(401).send({error:'Unauthorized'});}});
app.get('/health',async()=>({ok:true,service:'opass-api',time:new Date().toISOString()}));
registerAuthRoutes(app);registerCoreRoutes(app);registerAiRoutes(app);registerLiveRoutes(app);registerPaymentRoutes(app);
app.setErrorHandler((err,req,reply)=>{req.log.error(err);if((err as any).name==='ZodError')return reply.code(400).send({error:'Invalid request',details:(err as any).issues});return reply.code((err as any).statusCode??500).send({error:'Request failed'});});
const port = parseInt(process.env.PORT || String(env.API_PORT), 10);
await app.listen({port, host:'0.0.0.0'});
